// Umbra Privacy Adapter (replaces Privacy Cash)
export {
  // Types
  type UmbraNote,
  type EphemeralKey,
  type CompositeSecret,
  type FeeEstimate,
  type ClaimMode,
  type SupportedToken,
  type TokenInfo,
  type UmbraConfig,
  type ClaimModeInfo,
  // Legacy type aliases
  type DoubleHopNote,
  type SenderPrivacy,
  type RecipientPrivacy,
  type PrivacyLevel,
  type SenderPrivacyInfo,
  type RecipientPrivacyInfo,
  // Constants
  WSOL_MINT,
  UMBRA_FEE_BPS,
  UMBRA_BPS_DIVISOR,
  UMBRA_FEE_PERCENT,
  EPHEMERAL_GAS_BUFFER,
  WSOL_ATA_RENT,
  MIN_SEND_SOL,
  MIN_SEND_SPL,
  SPL_SOL_BUFFER,
  TOKEN_MINTS,
  CLAIM_MODES,
  SENDER_PRIVACY,
  RECIPIENT_PRIVACY,
  PRIVACY_LEVELS,
  // Ephemeral key generation
  generateEphemeralKey,
  decodeEphemeralSeed,
  generateCompositeSecret,
  decodeCompositeSecret,
  // Fee calculations
  calculateUmbraFees,
  calculateDepositForRecipientAmount,
  calculateRecipientReceives,
  estimatePrivateClaimReceives,
  calculateFees,
  calculateSPLFees,
  calculateSenderCost,
  calculateSPLRecipientReceives,
  calculateDepositForRecipientAmountLegacy as calculateDepositForRecipientAmountSOL,
  calculateSPLDepositForRecipientAmount,
  calculateTotalDeposit,
  // URL serialization
  serializeUmbraNote,
  deserializeUmbraNote,
  createClaimUrl,
  extractNoteFromUrl,
  // Legacy URL aliases
  serializeDoubleHopNote,
  deserializeDoubleHopNote,
  createDoubleHopClaimUrl,
  extractDoubleHopNoteFromUrl,
  // Token helpers
  getTokenInfo,
  getTokenFromMint,
  // Umbra SDK helpers
  getUmbraConfig,
  getUmbraConfigForNetwork,
  createUmbraClientFromKeypair,
  createUmbraClientFromWallet,
  createUmbraClientFromPrivateKey,
  ensureRegistered,
  getRelayer,
} from "./umbra-adapter";
