"use client";

/**
 * Legacy redirect: payroll claim links generated by older versions used
 * /payroll/claim#... — newer ones use the regular /claim#... URL so they
 * share UI with the rest of Hoppy. This page just forwards the URL hash.
 */

import { useEffect } from "react";

export default function PayrollClaimRedirect() {
  useEffect(() => {
    if (typeof window === "undefined") return;
    const hash = window.location.hash; // includes the leading '#'
    window.location.replace(`/claim${hash}`);
  }, []);

  return (
    <div className="min-h-screen flex items-center justify-center text-sm text-muted-foreground">
      Redirecting to claim…
    </div>
  );
}
