"use client";

/**
 * Legacy redirect: payroll claim links generated by older versions used
 * /payroll/claim#... — newer ones use the regular /claim#... URL so they
 * share UI with the rest of Hoppy. This page just forwards the URL hash.
 *
 * Belt-and-braces approach so a slow/broken hydration doesn't strand the
 * user on a "Redirecting…" screen forever:
 *   1. Inline <script> redirects immediately on parse (no React needed).
 *   2. useEffect retries on hydration in case the inline script is blocked.
 *   3. Clickable fallback <a> if both fail.
 */

import { useEffect } from "react";

const REDIRECT_SCRIPT = `
  (function () {
    try {
      var hash = window.location.hash || "";
      window.location.replace("/claim" + hash);
    } catch (e) {}
  })();
`;

export function PayrollClaimRedirect() {
  useEffect(() => {
    if (typeof window === "undefined") return;
    const hash = window.location.hash;
    window.location.replace(`/claim${hash}`);
  }, []);

  return (
    <>
      <script dangerouslySetInnerHTML={{ __html: REDIRECT_SCRIPT }} />
      <div className="min-h-screen flex flex-col items-center justify-center gap-4 text-center px-4">
        <p className="text-sm text-muted-foreground">Redirecting to claim…</p>
        <p className="text-xs text-muted-foreground/70">
          If this page doesn&apos;t redirect automatically,{" "}
          <a
            href="/claim"
            className="underline text-foreground hover:text-hop-600 dark:hover:text-hop-400"
            // The link can't carry the hash on the server, so we patch it
            // on the client. If JS is fully broken the user lands on /claim
            // hashless and sees the standard "Invalid link" UI instead of
            // staying stuck here.
            ref={(el) => {
              if (el && typeof window !== "undefined") {
                el.setAttribute(
                  "href",
                  `/claim${window.location.hash || ""}`,
                );
              }
            }}
          >
            click here
          </a>
          .
        </p>
      </div>
    </>
  );
}
